apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - go-app-rollout.yaml
  - go-app-rollout-service.yaml
  - go-app-hpa.yaml

images:
  - name: 288937191843.dkr.ecr.ap-south-1.amazonaws.com/go-app
    newTag: 042868971b9deaf14e8e02f072cb78901b433761