apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-app-rollout-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: go-rollout.devsecops.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go-app-rollout
                port:
                  number: 80
