apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - go-app
  - ingress.yaml

images:
  - name: 288937191843.dkr.ecr.ap-south-1.amazonaws.com/go-app
    newTag: dummy
